### ISSUE TITLE
tomdoc does not play nicely with RubyInline if multiple versions are installed

### ISSUE THREAD

**Issue by yesmar** [defunkt/tomdoc#7]
```
$ gem list | grep RubyInline
RubyInline (3.8.6, 3.7.0)
$ grep RubyInline tomdoc.gemspec 
  s.add_dependency     "RubyInline", "= 3.7.0"
```

This is what happens when I run tomdoc:

```
$ tomdoc lib/tomdoc/source_parser.rb -n token
/opt/local/lib/ruby/site_ruby/1.9.1/rubygems.rb:274:in `activate': can't activate RubyInline (= 3.7.0, runtime) for ["tomdoc-0.1.0"], already activated RubyInline-3.8.6 for ["ParseTree-3.0.5", "tomdoc-0.1.0"] (Gem::LoadError)
from /opt/local/lib/ruby/site_ruby/1.9.1/rubygems.rb:290:in `block in activate'
from /opt/local/lib/ruby/site_ruby/1.9.1/rubygems.rb:289:in `each'
from /opt/local/lib/ruby/site_ruby/1.9.1/rubygems.rb:289:in `activate'
from /opt/local/lib/ruby/site_ruby/1.9.1/rubygems.rb:1204:in `gem'
from /opt/local/bin/tomdoc:18:in `<main>'
```

Can you update the gemspec so that the RubyInline dependency is >= 3.7.0 instead of = 3.7.0 ?

**Comment by trans** [comment]
Fixed in recent commit (f139056491e398435972bf0d82bbc939c8c41b48).
